apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafkadata
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.220.4.49
    path: "/kafkadata"
