apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
          name: client
        env:
        - name : KAFKA_ZOOKEEPER_CONNECT
          value: zk-headless.default.svc.cluster.local
        - name : KAFKA_BROKER_ID
          value: "1"
        - name : KAFKA_ADVERTISED_LISTENERS
          value:  PLAINTEXT://kafka-0.kafka-headless.default.svc.cluster.local:9092
      volumes:
      - name: datadir
        persistentVolumeClaim:
         claimName: kafkadata

     

